<?php
function reporte_1() {

    $cartera = $_POST['cartera'];
    $fecha_desde = $_POST['fecha_desde'];
    $fecha_hasta = $_POST['fecha_hasta'];
    $fecha_desde_ts = DateTime::createFromFormat('d/m/Y', $fecha_desde);
    $fecha_hasta_ts = DateTime::createFromFormat('d/m/Y', $fecha_hasta);


      if ( $cartera == 0 ) {
        throw new Exception('Seleccione una cartera',1);
      }
      if ( $fecha_desde_ts > $fecha_hasta_ts ) {
        throw new Exception('el rango de fechas no es valido',1);
      }

  $query = "
DECLARE 
@FECHA_DESDE VARCHAR(10)
, @FECHA_HASTA VARCHAR(10)

SET @FECHA_DESDE = '".$fecha_desde."'
SET @FECHA_HASTA = '".$fecha_hasta."'

SELECT
MGA.CLI_DOCUMENTO_IDENTIDAD AS 'S14|DOCUMENTO'
, MGA.DIR_CODIGO AS 'S12|DIR_CODIGO'
, ROW_NUMBER() OVER(PARTITION BY MGA.CLI_DOCUMENTO_IDENTIDAD ORDER BY MGA.DIR_CODIGO ASC) AS 'N08|ORDEN'
, MGA.MEJ_EST AS 'S10|MEJOR ESTADO'
, MGA.TDI_DESCRIPCION AS 'S14|TIPO DIRECCION'
, MGA.TOR_DESCRIPCION AS 'S18|ORIGEN'
, MGA.DEPARTAMENTO AS 'S16|DEPARTAMENTO'
, MGA.PROVINCIA AS 'S18|PROVINCIA'
, MGA.DISTRITO AS 'S20|DISTRITO'
, REPLACE(MGA.DIR_DIRECCION,'\"','') AS 'S26|DIRECCION'
, CASE WHEN MGA.TIPIFICACION IS NULL THEN ISNULL(MGA.TIR_DESCRIPCION, '-') ELSE CONCAT(MGA.TIPIFICACION,'/',MGA.TIR_DESCRIPCION) END AS 'S22|RESULTADO GESTION'
, MGA.FECHA_MG AS 'S12|FECHA MEJOR GESTION'
, CASE WHEN MGA.TIR_DESCRIPCION IS NULL THEN '0' ELSE MGA.INSTENSIDAD END AS 'N12|INTENSIDAD'
, MGA.ULTIMO_CONTACTO AS 'S12|FECHA ULTIMA GESTION'
, REPLACE(MGA.GES_OBSERVACIONES,'\"','') AS 'S22|OBSERVACIONES'
FROM
(
SELECT
 CLI.CLI_DOCUMENTO_IDENTIDAD
, DIR.DIR_CODIGO
, ISNULL (RES.EST_VAL_DIR,'SG') AS MEJ_EST
, TPD.TDI_DESCRIPCION
, TOR.TOR_DESCRIPCION
, DIR.DIR_DIRECCION
, CASE DIR.UBI_CODIGO WHEN '' THEN DIR.DIR_DEPARTAMENTO  ELSE UBI.UBI_DEPARTAMENTO END AS DEPARTAMENTO
, CASE DIR.UBI_CODIGO WHEN '' THEN DIR.DIR_PROVINCIA  ELSE UBI.UBI_PROVINCIA END AS PROVINCIA
, CASE DIR.UBI_CODIGO WHEN '' THEN DIR.DIR_DISTRITO  ELSE UBI.UBI_DISTRITO END AS DISTRITO
, ISNULL(CONVERT(VARCHAR,MAX(GES.GES_FECHA) OVER(PARTITION BY DIR.DIR_CODIGO), 103),'') AS ULTIMO_CONTACTO
, ROW_NUMBER() OVER(PARTITION BY DIR.DIR_CODIGO ORDER BY RES.TIR_PESO ASC, GES.GES_FECHA DESC, GES.GES_CODIGO DESC) AS UNICO
, DENSE_RANK() OVER(PARTITION BY DIR.DIR_CODIGO ORDER BY RES.TIR_PESO DESC, GES.GES_FECHA ASC) AS INSTENSIDAD
, RANK() OVER(PARTITION BY DIR.DIR_CODIGO ORDER BY RES.TIR_PESO ASC, GES.GES_FECHA DESC, GES.GES_CODIGO DESC) AS M_GESTION
, ISNULL(CONVERT(VARCHAR,GES.GES_FECHA,103),'') AS FECHA_MG
, ISNULL(GES.GES_CODIGO,0) AS GES_CODIGO
, TRS.TIR_DESCRIPCION AS TIPIFICACION
, RES.TIR_DESCRIPCION
, ISNULL(GES.GES_OBSERVACIONES, '') AS GES_OBSERVACIONES
, RES.TIR_PESO
, CASE GES.SOL_CODIGO WHEN 0 THEN GES.TIR_CODIGO ELSE GES.SOL_CODIGO END AS NUEVO_CODIGO
FROM
COBRANZA.GCC_CLIENTE CLI
INNER JOIN COBRANZA.GCC_CUENTAS CUE ON CUE.CLI_CODIGO=CLI.CLI_CODIGO
INNER JOIN COBRANZA.GCC_BASEDET BDE ON BDE.CUE_CODIGO=CUE.CUE_CODIGO AND BDE.BAD_ESTADO_CUENTA='A'
INNER JOIN COBRANZA.GCC_BASE BAS ON BAS.BAS_CODIGO=BDE.BAS_CODIGO
INNER JOIN COBRANZA.GCC_CARTERAS CAR ON CAR.CAR_CODIGO=BAS.CAR_CODIGO AND CAR.CAR_CODIGO=".$cartera."
INNER JOIN COBRANZA.GCC_DIRECCIONES DIR ON DIR.CLI_CODIGO=CLI.CLI_CODIGO
INNER JOIN COBRANZA.GCC_TIPO_ORIGEN TOR ON DIR.TOR_CODIGO=TOR.TOR_CODIGO
INNER JOIN COBRANZA.GCC_TIPO_DIRECCION TPD ON DIR.TDI_CODIGO=TPD.TDI_CODIGO
LEFT JOIN COBRANZA.GCC_UBIGEO UBI ON UBI.UBI_CODIGO=DIR.UBI_CODIGO
LEFT JOIN COBRANZA.GCC_GESTIONES GES ON GES.DIR_CODIGO=DIR.DIR_CODIGO AND GES.TIG_CODIGO=7 AND GES.GES_FECHA BETWEEN CONVERT(DATE, @FECHA_DESDE,103) AND CONVERT(DATE,@FECHA_HASTA,103)
LEFT JOIN COBRANZA.GCC_TIPO_RESULTADO RES ON GES.SOL_CODIGO=RES.TIR_CODIGO OR (GES.SOL_CODIGO=0 AND GES.TIR_CODIGO=RES.TIR_CODIGO)
LEFT JOIN COBRANZA.GCC_TIPO_RESULTADO TRS ON GES.TIR_CODIGO=TRS.TIR_CODIGO AND GES.SOL_CODIGO <> 0
WHERE
DIR.DIR_ESTADO_REGISTRO='A'
) MGA
WHERE
MGA.UNICO=1
ORDER BY 1 ASC, 2 ASC;";

  $array_query_result = run_select_query_sqlser($query);
  return $array_query_result;
}
?>
