<?php

function reporte_1() {

  $cartera = $_POST['cartera'];
  if ( $cartera == 0 ) {
    throw new Exception('Seleccione una cartera',1);
  }
  $subcartera = $_POST['subcartera'];
  
  $query = "
 DECLARE
  @SUBCARTERA INT;
  SET
  @SUBCARTERA=".$subcartera."
  SELECT
  CLI.CLI_DOCUMENTO_IDENTIDAD AS 'S12|DOCUMENTO'
  , CUE.CUE_NROCUENTA AS 'S22|CUENTA'
  , CLI.CLI_NOMBRE_COMPLETO AS 'S35|CLIENTE'
  , SCA.SCA_DESCRIPCION AS 'S18|SUBCARTERA'
  , ISNULL(CONVERT(VARCHAR,ASI.ASI_FECHA_INICIO, 103),'') AS 'S12|FECHA ASIGNACION'
  , ISNULL(CONVERT(VARCHAR,ASI.ASI_FECHA_REGISTRO, 120),'') AS 'S22|FECHA REGISTRO'
  , ISNULL(UCAL.USU_LOGIN,'SIN ASIGNAR') AS 'S15|USUARIO CALL'
  , ISNULL(UCAM.USU_LOGIN,'SIN ASIGNAR') AS 'S15|USUARIO CAMPO'
  FROM
  COBRANZA.GCC_CLIENTE CLI
  INNER JOIN COBRANZA.GCC_CUENTAS CUE ON CUE.CLI_CODIGO=CLI.CLI_CODIGO
  INNER JOIN COBRANZA.GCC_BASEDET BDE ON BDE.CUE_CODIGO=CUE.CUE_CODIGO AND BDE.BAD_ESTADO_CUENTA='A'
  INNER JOIN COBRANZA.GCC_BASE BAS ON BAS.BAS_CODIGO=BDE.BAS_CODIGO AND BAS.CAR_CODIGO=".$cartera." AND (@SUBCARTERA=0 OR BAS.SCA_CODIGO=@SUBCARTERA)
  INNER JOIN COBRANZA.GCC_SUBCARTERAS SCA ON SCA.SCA_CODIGO=BAS.SCA_CODIGO
  LEFT JOIN COBRANZA.GCC_ASIGNACION ASI ON ASI.CUE_CODIGO=CUE.CUE_CODIGO AND ASI.ASI_ESTADO=1 AND ASI.ROL_CODIGO=4
  LEFT JOIN COBRANZA.GCC_USUARIO UCAL ON UCAL.USU_CODIGO=ASI.USU_CODIGO
  LEFT JOIN COBRANZA.GCC_ASIGNACION ASIC ON ASIC.CUE_CODIGO=CUE.CUE_CODIGO AND ASIC.ASI_ESTADO=1 AND ASIC.ROL_CODIGO=5
  LEFT JOIN COBRANZA.GCC_USUARIO UCAM ON UCAM.USU_CODIGO=ASIC.USU_CODIGO
  ORDER BY 1 ASC";

  $array_query_result = run_select_query_sqlser($query);
  return $array_query_result;
}
?>
