<?php

function reporte_1() {
//reporte telefonos progresivo
  $cartera = $_POST['cartera'];
//  $subcartera = $_POST['subcartera'];
  if ( $cartera == 0 ) {
    throw new Exception('Seleccione una cartera', 1);
  }

  $query = "
  SELECT
CLI.CLI_DOCUMENTO_IDENTIDAD AS 'S14|DOCUMENTO'
, CUE.CUE_NROCUENTA AS 'S22|CUENTA'
, SCA.SCA_DESCRIPCION AS 'S15|SUBCARTERA'
, USU.USU_LOGIN AS 'S15|USUARIO CALL'
, CASE TST.MEJ_CONTACTO WHEN 1 THEN 'CD' WHEN 2 THEN 'CI' WHEN 3 THEN 'NC' WHEN 4 THEN 'IN' ELSE '' END AS 'S15|CONTACTO PERIODO ACTUAL'
, PER.PER_CODIGO  AS 'S12|PERIODO ACTUAL'
--, CLI2.MAX1 AS 'S15|ULTIMA GESTION POR CLIENTE'
, CONVERT(VARCHAR,CLI2.MAX1,103) AS 'S15|ULTIMA GESTION POR CLIENTE'
, DATEDIFF(DAY,ISNULL(CLI2.MAX1,CUE.CUE_FECHA_REGISTRO),GETDATE()) AS 'N12|DIAS SIN GESTION'
FROM
COBRANZA.GCC_CUENTAS CUE
INNER JOIN COBRANZA.GCC_CLIENTE CLI ON CLI.CLI_CODIGO=CUE.CLI_CODIGO
INNER JOIN COBRANZA.GCC_BASEDET BDE ON BDE.CUE_CODIGO=CUE.CUE_CODIGO AND BDE.BAD_ESTADO_CUENTA='A'
INNER JOIN COBRANZA.GCC_BASE BAS ON BAS.BAS_CODIGO=BDE.BAS_CODIGO
INNER JOIN COBRANZA.GCC_SUBCARTERAS SCA ON SCA.SCA_CODIGO=BAS.SCA_CODIGO
LEFT JOIN COBRANZA.GCC_ASIGNACION ASI ON ASI.ROL_CODIGO=4 AND ASI.CUE_CODIGO=CUE.CUE_CODIGO AND ASI.ASI_ESTADO=1
LEFT JOIN COBRANZA.GCC_USUARIO USU ON USU.USU_CODIGO=ASI.USU_CODIGO
LEFT JOIN COBRANZA.GCC_PERIODO_SUBCARTERA PER ON PER.SCA_CODIGO=BAS.SCA_CODIGO AND PER.FLG_ESTADO=1
LEFT JOIN COBRANZA.GCC_CUENTA_STATUS_MENSUAL TST ON TST.CUE_CODIGO=CUE.CUE_CODIGO AND TST.CUE_PERIODO=PER.PER_CODIGO
LEFT JOIN (
SELECT
CLI3.CLI_CODIGO
, MAX(CUE2.CUE_ULTIMA_GESTION) AS MAX1
FROM
COBRANZA.GCC_CLIENTE CLI3
INNER JOIN COBRANZA.GCC_CUENTAS CUE2 ON CUE2.CLI_CODIGO=CLI3.CLI_CODIGO
GROUP BY CLI3.CLI_CODIGO
) CLI2 ON CLI2.CLI_CODIGO=CUE.CLI_CODIGO
WHERE
BAS.PRV_CODIGO=2
ORDER BY 1 ASC--, 5 DESC ";

  $array_query_result = run_select_query_sqlser($query);
  return $array_query_result;
}

?>
