<?php
function reporte_1() {
//reporte telefonos progresivo
  $cartera = $_POST['cartera'];
  $subcartera = $_POST['subcartera'];
  if ( $cartera == 0 ) {
    throw new Exception('Seleccione una cartera', 1);
  }

  $query = "
  DECLARE
  @SUBCARTERA INT;
  SET
  @SUBCARTERA=".$subcartera."
  SELECT
  REPLACE(TEL.TEL_NUMERO, CHAR(9), '') AS 'S10|telefono'
, CCUE.CUE_NROCUENTA AS 'S22|cuenta'
, REPLACE(TEL.TEL_NUMERO, CHAR(9), '') AS 'S10|numero'
, CCUE.CUE_CODIGO as 'S10|CUE_CODIGO'
, TEL.TEL_CODIGO as 'S10|TEL_CODIGO'
, CCUE.CLI_DOCUMENTO_IDENTIDAD AS 'S15|DOCUMENTO'
, ORI.TOR_DESCRIPCION AS 'S15|ORIGEN'
, TEL.TEL_ESTADO_VALIDEZ AS 'S10|ESTADO'
, TEL.TEL_OBSERVACIONES AS 'S20|OBSERVACIONES'
, SCA.SCA_DESCRIPCION AS 'S15|DESCRIPCION'
FROM
COBRANZA.GCC_TELEFONOS TEL
INNER JOIN (
SELECT
CUE.CLI_CODIGO
, CUE.CUE_CODIGO
, CUE.CUE_NROCUENTA
, CLI.CLI_DOCUMENTO_IDENTIDAD
, BDE.BAD_DEUDA_SALDO
, BAS.SCA_CODIGO
, ROW_NUMBER() OVER(PARTITION BY CLI.CLI_DOCUMENTO_IDENTIDAD ORDER BY BDE.BAD_DEUDA_SALDO DESC) AS ORDEN
FROM
COBRANZA.GCC_CUENTAS CUE
INNER JOIN COBRANZA.GCC_CLIENTE CLI ON CLI.CLI_CODIGO=CUE.CLI_CODIGO
INNER JOIN COBRANZA.GCC_BASEDET BDE ON BDE.CUE_CODIGO=CUE.CUE_CODIGO AND BDE.BAD_ESTADO_CUENTA='A'
INNER JOIN COBRANZA.GCC_BASE BAS ON BAS.BAS_CODIGO=BDE.BAS_CODIGO AND BAS.CAR_CODIGO=".$cartera." AND (@SUBCARTERA=0 OR BAS.SCA_CODIGO=@SUBCARTERA)
) CCUE ON CCUE.CLI_CODIGO=TEL.CLI_CODIGO AND CCUE.ORDEN=1
INNER JOIN COBRANZA.GCC_SUBCARTERAS SCA ON SCA.SCA_CODIGO=CCUE.SCA_CODIGO
LEFT JOIN COBRANZA.GCC_TIPO_ORIGEN ORI ON ORI.TOR_CODIGO=TEL.TOR_CODIGO
WHERE
TEL.TEL_ESTADO_REGISTRO='A'
ORDER BY 5 ASC, 2 DESC";

  $array_query_result = run_select_query_sqlser($query);
  return $array_query_result;

}
?>
