<?php
function reporte_1($cartera, $fecha_desde, $fecha_hasta) {

  //conectarse al Sql Server
  //sqlsrv_configure("LogSubsystems", SQLSRV_LOG_SYSTEM_ALL);
  //sqlsrv_configure("LogSeverity", SQLSRV_LOG_SEVERITY_ALL);
  ini_set('sqlsrv.ClientBufferMaxKBSize','524288');
  $conn = conectar_mssql();
  $query = "
DECLARE 
@FECHA_DESDE VARCHAR(10)
, @FECHA_HASTA VARCHAR(10)

SET @FECHA_DESDE = '".$fecha_desde."'
SET @FECHA_HASTA = '".$fecha_hasta."'

SELECT
MGA.CLI_DOCUMENTO_IDENTIDAD AS DOCUMENTO
, MGA.DIR_CODIGO
, ROW_NUMBER() OVER(PARTITION BY MGA.CLI_DOCUMENTO_IDENTIDAD ORDER BY MGA.DIR_CODIGO ASC) AS ORDEN
, MGA.MEJ_EST AS 'MEJOR ESTADO'
, MGA.TDI_DESCRIPCION AS 'TIPO DIRECCION'
, MGA.TOR_DESCRIPCION AS ORIGEN
, MGA.DEPARTAMENTO
, MGA.PROVINCIA
, MGA.DISTRITO
, REPLACE(MGA.DIR_DIRECCION,'\"','') AS DIRECCION
, CASE WHEN MGA.TIPIFICACION IS NULL THEN ISNULL(MGA.TIR_DESCRIPCION, '') ELSE CONCAT(MGA.TIPIFICACION,'/',MGA.TIR_DESCRIPCION) END AS RESULTADO_GESTION
, MGA.FECHA_MG
, CASE WHEN MGA.TIR_DESCRIPCION IS NULL THEN '0' ELSE MGA.INSTENSIDAD END AS INTENSIDAD
, MGA.ULTIMO_CONTACTO AS FECHA_ULT_GESTION
, REPLACE(MGA.GES_OBSERVACIONES,'\"','') AS OBSERVACIONES
FROM
(
SELECT
 CLI.CLI_DOCUMENTO_IDENTIDAD
, DIR.DIR_CODIGO
, ISNULL (RES.EST_VAL_DIR,'SG') AS MEJ_EST
, TPD.TDI_DESCRIPCION
, TOR.TOR_DESCRIPCION
, DIR.DIR_DIRECCION
, CASE DIR.UBI_CODIGO WHEN '' THEN DIR.DIR_DEPARTAMENTO  ELSE UBI.UBI_DEPARTAMENTO END AS DEPARTAMENTO
, CASE DIR.UBI_CODIGO WHEN '' THEN DIR.DIR_PROVINCIA  ELSE UBI.UBI_PROVINCIA END AS PROVINCIA
, CASE DIR.UBI_CODIGO WHEN '' THEN DIR.DIR_DISTRITO  ELSE UBI.UBI_DISTRITO END AS DISTRITO
, ISNULL(CONVERT(VARCHAR,MAX(GES.GES_FECHA) OVER(PARTITION BY DIR.DIR_CODIGO), 103),'') AS ULTIMO_CONTACTO
, ROW_NUMBER() OVER(PARTITION BY DIR.DIR_CODIGO ORDER BY RES.TIR_PESO ASC, GES.GES_FECHA DESC, GES.GES_CODIGO DESC) AS UNICO
, DENSE_RANK() OVER(PARTITION BY DIR.DIR_CODIGO ORDER BY RES.TIR_PESO DESC, GES.GES_FECHA ASC) AS INSTENSIDAD
, RANK() OVER(PARTITION BY DIR.DIR_CODIGO ORDER BY RES.TIR_PESO ASC, GES.GES_FECHA DESC, GES.GES_CODIGO DESC) AS M_GESTION
, ISNULL(CONVERT(VARCHAR,GES.GES_FECHA,103),'') AS FECHA_MG
, ISNULL(GES.GES_CODIGO,0) AS GES_CODIGO
, TRS.TIR_DESCRIPCION AS TIPIFICACION
, RES.TIR_DESCRIPCION
, ISNULL(GES.GES_OBSERVACIONES, '') AS GES_OBSERVACIONES
, RES.TIR_PESO
, CASE GES.SOL_CODIGO WHEN 0 THEN GES.TIR_CODIGO ELSE GES.SOL_CODIGO END AS NUEVO_CODIGO
FROM
COBRANZA.GCC_CLIENTE CLI
INNER JOIN COBRANZA.GCC_CUENTAS CUE ON CUE.CLI_CODIGO=CLI.CLI_CODIGO
INNER JOIN COBRANZA.GCC_BASEDET BDE ON BDE.CUE_CODIGO=CUE.CUE_CODIGO AND BDE.BAD_ESTADO_CUENTA='A'
INNER JOIN COBRANZA.GCC_BASE BAS ON BAS.BAS_CODIGO=BDE.BAS_CODIGO
INNER JOIN COBRANZA.GCC_CARTERAS CAR ON CAR.CAR_CODIGO=BAS.CAR_CODIGO AND CAR.CAR_CODIGO=".$cartera."
INNER JOIN COBRANZA.GCC_CLIENTE CL2 ON CL2.CLI_DOCUMENTO_IDENTIDAD=CLI.CLI_DOCUMENTO_IDENTIDAD
INNER JOIN COBRANZA.GCC_DIRECCIONES DIR ON DIR.CLI_CODIGO=CL2.CLI_CODIGO
INNER JOIN COBRANZA.GCC_TIPO_ORIGEN TOR ON DIR.TOR_CODIGO=TOR.TOR_CODIGO
INNER JOIN COBRANZA.GCC_TIPO_DIRECCION TPD ON DIR.TDI_CODIGO=TPD.TDI_CODIGO
LEFT JOIN COBRANZA.GCC_UBIGEO UBI ON UBI.UBI_CODIGO=DIR.UBI_CODIGO
LEFT JOIN COBRANZA.GCC_GESTIONES GES ON GES.DIR_CODIGO=DIR.DIR_CODIGO AND GES.TIG_CODIGO=7 AND GES.GES_FECHA BETWEEN CONVERT(DATE, @FECHA_DESDE,103) AND CONVERT(DATE,@FECHA_HASTA,103)
LEFT JOIN COBRANZA.GCC_TIPO_RESULTADO RES ON GES.SOL_CODIGO=RES.TIR_CODIGO OR (GES.SOL_CODIGO=0 AND GES.TIR_CODIGO=RES.TIR_CODIGO)
LEFT JOIN COBRANZA.GCC_TIPO_RESULTADO TRS ON GES.TIR_CODIGO=TRS.TIR_CODIGO AND GES.SOL_CODIGO <> 0
WHERE
DIR.DIR_ESTADO_REGISTRO='A'
) MGA
WHERE
MGA.UNICO=1
ORDER BY 1 ASC, 2 ASC;";
  
  $result_query = sqlsrv_query( $conn, $query, PARAMS_MSSQL_QUERY, OPTIONS_MSSQL_QUERY );
//  if (!$result_query) {
//    throw new Exception('No se pudo completar la consulta11',11);
   // echo "6";
  //}

  //throw new Exception('No se pudo completar la consulta11',11);
    if( ($errors = sqlsrv_errors() ) != null) {
        foreach( $errors as $error ) {
            echo "SQLSTATE: ".$error[ 'SQLSTATE']."<br />";
            echo "code: ".$error[ 'code']."<br />";
            echo "message: ".$error[ 'message']."<br />";
        }
        echo $query;
        print_r( $errors, false);
       // echo ini_get('sqlsrv.ClientBufferMaxKBSize');
     exit;
}
//       if ($result_query) {
//     $rows = sqlsrv_has_rows( $result_query );
//
//   if ($rows === true)
//      echo "There are rows. <br />";
//   else 
//      echo "There are no rows. <br />";
//}
  $array_query_result = array();
  $header = array();
 foreach(sqlsrv_field_metadata($result_query) as $meta) {

  $header[] = $meta['Name'];
}
$array_query_result[] = $header;
  //print_r($header);
  while( $row = sqlsrv_fetch_array($result_query, SQLSRV_FETCH_NUMERIC) ) {
  $array_query_result[] = $row;

  }
 // print_r($array_query_result);
  sqlsrv_free_stmt($result_query);
return $array_query_result;
}
?>

