<?php

function reporte_1() {
    if (isset($_POST['proveedor'])) {
        $proveedor = $_POST['proveedor'];
        if ( $proveedor == 0 ) {
            throw new Exception('Seleccione una cartera', 1);
        }//endif
    }//endif

    $query = "
    DECLARE
    @COLUMNA1 VARCHAR(80)
    , @COLUMNA2 VARCHAR(100)

    SET @COLUMNA1 = ', CASE WHEN PAL.[XX] > 0 THEN  PAL.[XX] ELSE NULL END AS ''S10|YY'''
    SET @COLUMNA2 = ', SUM(CASE WHEN TGE.SCA_CODIGO=XX THEN 1 ELSE 0 END) AS ''YY'''

    SELECT
     REPLACE(REPLACE(@COLUMNA1, 'YY', SCA.SCA_DESCRIPCION), 'XX', SCA.SCA_DESCRIPCION)AS SELECT1
    , REPLACE(REPLACE(@COLUMNA2,'YY' , SCA.SCA_DESCRIPCION ), 'XX',  CAST(SCA.SCA_CODIGO AS varchar(3) )) AS SELECT2
    FROM
        COBRANZA.GCC_PROVEEDOR PRV
        INNER JOIN COBRANZA.GCC_CARTERAS CAR ON CAR.PRV_CODIGO=PRV.PRV_CODIGO AND CAR.CAR_ESTADO_REGISTRO='A'
        INNER JOIN COBRANZA.GCC_SUBCARTERAS SCA ON SCA.CAR_CODIGO=CAR.CAR_CODIGO AND SCA.SCA_ESTADO_REGISTRO='A'
        WHERE
        PRV.PRV_ESTADO_REGISTRO='A'
        AND PRV.PRV_CODIGO=$proveedor
    ORDER BY SCA_CODIGO";

    $array_query_result = run_select_query_sqlser($query);

    //si hay carteras activas
    if ( isset($array_query_result['resultado']) ) {
        //Ej de Select1:     , PAL.[JUDICIAL] AS 'S10|JUDICIAL'
        //                   , PAL.[CASTIGO] AS 'S10|CASTIGO'
        $select1 = '';
        //Ej de select2:
        // , SUM(CASE WHEN TGE.SCA_CODIGO=10 THEN 1 ELSE 0 END) AS 'JUDICIAL'
        // , SUM(CASE WHEN TGE.SCA_CODIGO=13 THEN 1 ELSE 0 END) AS 'CASTIGO'
        $select2 = '';

        $array = $array_query_result['resultado'];

        foreach ($array as $value) { //VALUE = FILA
            foreach ($value as $key => $value) {//KEY = COLUMNA
                if ($key == 0) {// PRIMERA COLUMNA
                    $select1 .= $value;
                    $select1 .= "\n";
                }elseif ( $key == 1 ) { //SEGUNDA COLUMNA
                    $select2 .= $value;
                    $select2 .= "\n";
                }//if..else
            }//foreach de cada columna
        }//foreach de cada fila
    }//if

    $query = "
    SELECT
    CASE WHEN SALIENTE > 0 THEN 'SALIENTE'
    	ELSE '' END AS 'S15|SALIENTE'
    , CASE WHEN CAMPO > 0 THEN 'CAMPO'
    	ELSE '' END AS 'S15|CAMPO'
    , CASE WHEN COURIER > 0 THEN 'COURIER'
    	ELSE '' END AS 'S15|COURIER'
    , CASE WHEN VISITA_OFICINA > 0 THEN 'VISITA OFICINA'
    	ELSE '' END AS 'S15|VISITA OFICINA'
    , CASE WHEN OTRAS_HERRAMIENTAS > 0 THEN 'OTRAS HERRAMIENTAS'
    	ELSE '' END AS 'S15|OTRAS HERRAMIENTAS'
    , PAL.COD_RESP AS 'S08|COD RESP'
    , PAL.RESPUESTA AS 'S35|RESPUESTA'
    , PAL.COD_SOL AS 'S08|COD SOL'
    , PAL.SOLUCION AS 'S35|SOLUCION'
    , ISNULL(PAL.PESO_SOL, PAL.PESO_RESP) AS 'S08|PESO'
    , ISNULL(PAL.PRIORIDAD_SOL, PAL.PRIORIDAD_RESP) AS 'S10|PRIORIDAD'
    , ISNULL(PAL.EST_TEL_SOL, PAL.EST_DIR_RESP) AS 'S08|ESTADO TEL'
    , ISNULL(PAL.EST_DIR_SOL, PAL.EST_DIR_RESP) AS 'S08|ESTADO DIR'
    , CASE ISNULL(PAL.TIPO_CONTAC_SOL, PAL.TIPO_CONTAC_RESP)
    	WHEN 1 THEN 'CD'
    	WHEN 2 THEN 'CI'
    	WHEN 3 THEN 'NC'
    	WHEN 4 THEN 'IN' END AS 'S10|TIPO CONTACTO'
    , PAL.FLG_COMPROMISO AS 'S08|COMPROMISO'
    , ISNULL(PAL.COD_GESTION_SOL, PAL.COD_GESTION_RESP) AS 'S15|COD GESTION CLIENTE'
    , ISNULL(PAL.PRIORIDAD2_SOL, PAL.PRIORIDAD2_RESP) AS 'S10|PRIORIDAD2'
    $select1
    FROM (
    SELECT
     SUM(CASE WHEN TGE.TIG_CODIGO=5 THEN 1 ELSE 0 END) AS SALIENTE
    , SUM(CASE WHEN TGE.TIG_CODIGO=7 THEN 1 ELSE 0 END) AS CAMPO
    , SUM(CASE WHEN TGE.TIG_CODIGO=8 THEN 1 ELSE 0 END) AS COURIER
    , SUM(CASE WHEN TGE.TIG_CODIGO=9 THEN 1 ELSE 0 END) AS VISITA_OFICINA
    , SUM(CASE WHEN TGE.TIG_CODIGO=10 THEN 1 ELSE 0 END) AS OTRAS_HERRAMIENTAS
    , TGE.TIR_CODIGO AS COD_RESP
    , TRE1.TIR_DESCRIPCION AS RESPUESTA
    , SOL.TIR_CODIGO AS COD_SOL
    , SOL.TIR_DESCRIPCION AS SOLUCION
    , TRE1.TIR_PESO AS PESO_RESP
    , SOL.TIR_PESO AS PESO_SOL
    , SOL.TIR_PRIORIDAD AS PRIORIDAD_SOL
    , TRE1.TIR_PRIORIDAD AS PRIORIDAD_RESP
    , SOL.EST_VAL_TEL AS EST_TEL_SOL
    , TRE1.EST_VAL_TEL AS EST_TEL_RESP
    , SOL.EST_VAL_DIR AS EST_DIR_SOL
    , TRE1.EST_VAL_DIR AS EST_DIR_RESP
    , SOL.TIR_TIPO_CONTAC AS TIPO_CONTAC_SOL
    , TRE1.TIR_TIPO_CONTAC AS TIPO_CONTAC_RESP
    , SOL.FLG_COMPROMISO
    , SOL.TIR_COD_GESTION AS COD_GESTION_SOL
    , TRE1.TIR_COD_GESTION AS COD_GESTION_RESP
    , SOL.TIR_CODIGOS_RESP AS PRIORIDAD2_SOL
    , TRE1.TIR_CODIGOS_RESP AS PRIORIDAD2_RESP
    $select2
    FROM
    COBRANZA.GCC_BASE BAS
    INNER JOIN COBRANZA.GCC_PROVEEDOR PRV ON PRV.PRV_CODIGO=BAS.PRV_CODIGO AND PRV.PRV_ESTADO_REGISTRO='A'
    INNER JOIN COBRANZA.GCC_SUBCARTERAS SCA ON SCA.SCA_CODIGO=BAS.SCA_CODIGO AND SCA.SCA_ESTADO_REGISTRO='A'
    INNER JOIN COBRANZA.GCC_TGEST_TRESU TGE ON TGE.SCA_CODIGO=SCA.SCA_CODIGO AND TGE.TGR_ESTADO_REGISTRO='A'
    INNER JOIN COBRANZA.GCC_TIPO_RESULTADO TRE1 ON TRE1.TIR_CODIGO=TGE.TIR_CODIGO
    LEFT JOIN COBRANZA.GCC_TIPO_RESULTADO SOL ON SOL.TIR_PADRE=TRE1.TIR_CODIGO
    WHERE
    PRV.PRV_CODIGO=$proveedor AND TGE.TIG_CODIGO IN (5, 7, 8, 9, 10)
    GROUP BY TGE.TIR_CODIGO,
    		TRE1.TIR_DESCRIPCION,
    		SOL.TIR_CODIGO,
    		TRE1.TIR_PESO,
    		SOL.TIR_PESO,
    		SOL.TIR_PRIORIDAD, TRE1.TIR_PRIORIDAD,
    		SOL.EST_VAL_TEL, TRE1.EST_VAL_TEL,
    		SOL.EST_VAL_DIR, TRE1.EST_VAL_DIR,
    		SOL.TIR_TIPO_CONTAC, TRE1.TIR_TIPO_CONTAC,
    		SOL.FLG_COMPROMISO,
    		SOL.TIR_COD_GESTION, TRE1.TIR_COD_GESTION,
    		SOL.TIR_CODIGOS_RESP , TRE1.TIR_CODIGOS_RESP,
    		SOL.TIR_DESCRIPCION) PAL
    ORDER BY PAL.SALIENTE DESC, PAL.COD_RESP ASC";

    $array_query_result = run_select_query_sqlser($query);
    return $array_query_result;
}
 ?>
